package com.syzc.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("answer", "id", Answer.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("comment", "id", Comment.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("posts", "id", Posts.class);
		arp.addMapping("question", "id", Question.class);
		arp.addMapping("record", "id", Record.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_session", "id", UserSession.class);
	}
}


