package com.syzc.model;

import com.syzc.model.base.BasePosts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Posts extends BasePosts<Posts> {
	public static final Posts dao = new Posts().dao();
}

