package com.syzc.model;

import com.syzc.model.base.BaseRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Record extends BaseRecord<Record> {
	public static final Record dao = new Record().dao();
}

