package com.syzc.model;

import com.syzc.model.base.BaseUserSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSession extends BaseUserSession<UserSession> {
	public static final UserSession dao = new UserSession().dao();
}

