package com.syzc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	public void setOriginalName(java.lang.String originalName) {
		set("original_name", originalName);
	}
	
	public java.lang.String getOriginalName() {
		return getStr("original_name");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
	}
	
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}
	
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	public void setNewName(java.lang.String newName) {
		set("new_name", newName);
	}
	
	public java.lang.String getNewName() {
		return getStr("new_name");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedBy(java.math.BigInteger createdBy) {
		set("CREATED_BY", createdBy);
	}
	
	public java.math.BigInteger getCreatedBy() {
		return get("CREATED_BY");
	}
	
	public void setCreatedTime(java.util.Date createdTime) {
		set("CREATED_TIME", createdTime);
	}
	
	public java.util.Date getCreatedTime() {
		return getDate("CREATED_TIME");
	}
	
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("UPDATED_TIME", updatedTime);
	}
	
	public java.util.Date getUpdatedTime() {
		return getDate("UPDATED_TIME");
	}
	
}

