package com.syzc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedTime(java.util.Date createdTime) {
		set("CREATED_TIME", createdTime);
	}
	
	public java.util.Date getCreatedTime() {
		return getDate("CREATED_TIME");
	}
	
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("UPDATED_TIME", updatedTime);
	}
	
	public java.util.Date getUpdatedTime() {
		return getDate("UPDATED_TIME");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setFileId(java.lang.Long fileId) {
		set("file_id", fileId);
	}
	
	public java.lang.Long getFileId() {
		return getLong("file_id");
	}
	
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}
	
	public void setLikes(java.lang.Integer likes) {
		set("likes", likes);
	}
	
	public java.lang.Integer getLikes() {
		return getInt("likes");
	}
	
}

