package com.syzc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserSession<M extends BaseUserSession<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	public void setUserId(java.math.BigInteger userId) {
		set("user_id", userId);
	}
	
	public java.math.BigInteger getUserId() {
		return get("user_id");
	}
	
	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}
	
	public java.lang.String getSessionId() {
		return getStr("session_id");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	public void setCreatedTime(java.util.Date createdTime) {
		set("CREATED_TIME", createdTime);
	}
	
	public java.util.Date getCreatedTime() {
		return getDate("CREATED_TIME");
	}
	
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("UPDATED_TIME", updatedTime);
	}
	
	public java.util.Date getUpdatedTime() {
		return getDate("UPDATED_TIME");
	}
	
}

